### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ondrejbouda** [ondrejbouda/php7backport#1]
- [x] return changed node from visitor - problem with constructors, where the input node is class, but changed node is ClassMethod
- [x] better handling of invalidating nodes - post traversal maybe?
- [x] fix situation, when a node changes twice (e.g. constructor + return type) - then only one of them renders
